# Fondamenti di Pytorch

## Effettuiamo l'import delle librerie utilizzate nell'esercitazione.

In [1]:
import torch

Di seguito i riferimenti alle pagine di documentazione, sempre utiliti:

* Rif: [pytorch](https://pytorch.org/docs/stable/index.html)

Aggiungiamo alcune funzioni di utilita' per semplificare la scrittura del codice.

In [2]:
def info(t : torch.Tensor):
    print(f'\n*****')
    print(f'Valore:\n{t}\n')
    print(f'Tipo pytohn\t: {type(t)}')
    print(f'Tipo\t\t: {t.dtype}')
    print(f'Dimensioni\t: {t.ndim}')
    print(f'Forma\t\t: {t.shape}')
    print(f'Dispositivo\t: {t.device}')
    print(f'*****\n')

## _Quando si ha a disposizione un device, e' possibile utilizzare i tensori anche al di fuori della cpu._

Partiamo creando un tensore di esempio senza specificare altro,

In [3]:
sample_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])

In questo caso il tensore stara' su cpu, verifichiamolo.

In [4]:
info(sample_tensor)


*****
Valore:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tipo pytohn	: <class 'torch.Tensor'>
Tipo		: torch.int64
Dimensioni	: 2
Forma		: torch.Size([3, 2])
Dispositivo	: cpu
*****



## _Verificare la presenza del device e' il primo passo per poterlo utilizzare._

_pytorch_ mette a disposizione un sotto-modulo, _torch.cuda_, che fornisce metodi dedicati a fare questi controlli.

Rif: [torch.cuda](https://pytorch.org/docs/stable/cuda.html)

Per prima cosa controlliamo se un device abilitato ad usare CUDA e' presente. Per farlo utilizziamo il metodo **is_available** che con un valore booleano ci restituisce questa informazione.

Rif: [is_available](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html)

In [5]:
torch.cuda.is_available()


True

Possono essere presenti anche piu' device abilitati nel sistema. Per sapere quanti, il metodo **device_count** ci viene in aiuto.

Rif: [device_count](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html)

In [6]:
torch.cuda.device_count()

1

## _Un tensore, puo' essere quindi spostato su di un altro device disponibile._

Per farlo si ha a disposizione il metodo _to_ della classe **torch.Tensor**. A questo puo' essere specificato il device ed eventualmente anche l'indice.

Rif: [to](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html)

In [7]:
sample_tensor_gpu = sample_tensor.to("cuda")
info(sample_tensor_gpu)


*****
Valore:
tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0')

Tipo pytohn	: <class 'torch.Tensor'>
Tipo		: torch.int64
Dimensioni	: 2
Forma		: torch.Size([3, 2])
Dispositivo	: cuda:0
*****



Possiamo fare lo stesso, specificando anche l'indice.

In [8]:
sample_tensor_gpu_2 = sample_tensor.to("cuda:0")
info(sample_tensor_gpu_2)


*****
Valore:
tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0')

Tipo pytohn	: <class 'torch.Tensor'>
Tipo		: torch.int64
Dimensioni	: 2
Forma		: torch.Size([3, 2])
Dispositivo	: cuda:0
*****



Riportarlo su cpu e' altrettanto semplice.

In [9]:
sample_tensor_cpu = sample_tensor_gpu.to("cpu")
info(sample_tensor_cpu)


*****
Valore:
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tipo pytohn	: <class 'torch.Tensor'>
Tipo		: torch.int64
Dimensioni	: 2
Forma		: torch.Size([3, 2])
Dispositivo	: cpu
*****



## _Numpy non supporta la gpu quindi il passaggio da tensore a numpy array e' invalido se il tensore sta su gpu._

Il seguente codice, se eseguito, produrra' errore.

In [10]:
# sample_tensor_numpy = sample_tensor_gpu.numpy()

Riportare il tensore su cpu prima della conversione risolvera' il problema. Per ottenere una copia del tensore spostato in memoria cpu e' possibile utilizzare il metodo _cpu_ sul tensore stesso.

Rif: [cpu](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html)

In [11]:
sample_tensor_numpy = sample_tensor_gpu.cpu().numpy()

## _I tensori possono venire creati, direttamente, su di un dispositivo CUDA abilitato._

Ne possiamo vedere un esempio aggiungendo il parametro _device_ durante la creazione.

In [12]:
sample_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]], device="cuda")
info(sample_tensor)


*****
Valore:
tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0')

Tipo pytohn	: <class 'torch.Tensor'>
Tipo		: torch.int64
Dimensioni	: 2
Forma		: torch.Size([3, 2])
Dispositivo	: cuda:0
*****

